### ISSUE TITLE
Should this go in gpuweb/proposals?

### ISSUE THREAD

**Issue by grorg** [gpuweb/nxt-standalone#1]
I'm not sure what the best way to store vendor proposals is. I created a gpuweb/proposals repository and put Apple's stuff there. Should this move there too?

**Comment by Kangz** [comment]
Good question, I'm not sure exactly what shape a vendor proposal should be but I think this isn't one and it shouldn't go in gpuweb/proposals:

- This is a prototype and doesn't have any formal specification, not even in IDL form (though it can generate one)
- It is missing key features like renderpasses / memory barriers / buffer mapping
- I'm not sure we want to make proposals and choose one, but more share our experience and come up with a design together by borrowing bits and pieces of different prototypes.
- We will probably keep growing the prototype and it would be easier it is in a standalone repository.

We will see how we can make something that looks more like a proposal. My first idea is a document that references this repository and talks about our initial ideas for the missing features. What do you think?

**Comment by kainino0x** [comment]
While I don't like the term "proposal" for what we have, I think it's useful to have a place to collect all of the prototypes so they can be looked at together.

Maybe a "Prototypes"/"Experiments"/etc section of README.md in one of the other repositories, that links to some file nxt-standalone/README and to Apple's proposal?

**Comment by grorg** [comment]
Yeah, sounds good.
