### ISSUE TITLE
Provide binaries of nxt-chromium initial drop..

### ISSUE THREAD

**Issue by oscarbg** [gpuweb/nxt-standalone#2]
Hi,
this issue should be put in https://github.com/gpuweb/nxt-chromium repo but there issues can't be created so posting here..
There are instructions for building this chromium branch but seems overkill for only playing with this WebGPU proposal.. better would be if binaries say for Windows and Macos could be provided of the initial drop..

**Comment by Kangz** [comment]
Done in https://github.com/gpuweb/nxt-chromium/commit/28ff80849bd5fa01271f13aee5482bae85ec559c
Also enabled issues for the repo.

Note that the API is extremely barebones right now, and just good enough to do small demos. Also the NXT objects don't count towards the GC memory usage so it leads to situation that look like memory leaks in the GPU process.
